name: Test Reusable Caller

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    uses: dgbarreto/stockapp-app/.github/workflows/test-reusable.yml@debug/minimal-reusable
    with:
      module: quotes
      use-konan-cache: true
    secrets:
      GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
